awww/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("coding.urls")),
]

coding/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "coding"
urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="coding/login.html", redirect_authenticated_user=True), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", views.index, name="index"),
    path("file/<int:file_id>/", views.file, name="file"),
    path("add/folder/", views.add_folder, name="add/folder"),
    path("add/file/", views.add_file, name="add/file"),
    path("delete/folder/<int:folder_id>/", views.delete_folder, name="delete/folder"),
    path("delete/file/<int:file_id>/", views.delete_file, name="delete/file"),
    path("compile/<int:file_id>/", views.compile, name="compile"),
    path("save/<int:file_id>/", views.save_file, name="save"),
    # path("delete/section/<int:file_id>/<int:section_id>/", views.delete_section, name="delete/section"),
    # path("add/section/<int:file_id>/", views.add_section, name="add/section"),
    path("download/<int:file_id>/", views.download, name="download"),
    path("standard/", views.standard, name="standard"),
    path("optymalizacje/", views.optymalizacje, name="optymalizacje"),
    path("procesor/", views.procesor, name="procesor"),
    path("zalezne/", views.zalezne, name="zalezne"),
]

coding/forms.py
from django import forms
from .sdcc_options import *

class StandardForm(forms.Form):
    legend = "Wybierz standard kodu źródłowego:"
    standard = forms.ChoiceField(widget=forms.RadioSelect, choices=STANDARD_CHOICES)

class OptymalizacjeForm(forms.Form):
    legend = "Wybierz optymalizacje:"
    optymalizacje = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,choices=OPTYMALIZACJE_CHOICES, required=False)

class ProcesorForm(forms.Form):
    legend = "Wybierz procesor:"
    procesor = forms.ChoiceField(widget=forms.RadioSelect, choices=PROCESOR_CHOICES)

class MCS51Form(forms.Form):
    legend = "Wybierz opcje dla procesora MCS51:"
    mcs51 = forms.ChoiceField(widget=forms.RadioSelect, choices=MCS51_CHOICES)

class Z80Form(forms.Form):
    legend = "Wybierz opcje dla procesora Z80:"
    z80 = forms.ChoiceField(widget=forms.RadioSelect,choices=Z80_CHOICES)

class STM8Form(forms.Form):
    legend = "Wybierz opcje dla procesora STM8:"
    stm8 = forms.ChoiceField(widget=forms.RadioSelect, choices=STM8_CHOICES)

class FileUploadForm(forms.Form):
    file_name = forms.CharField(label='Nazwa pliku (opcjonalnie)', max_length=100, required=False, widget = forms.TextInput( attrs={'id': 'file_name'}))
    file = forms.FileField(label='Plik', widget = forms.FileInput( attrs={'class': 'file-input', 'accept': '.c', 'id': 'file_src'}))    

class FolderUploadForm(forms.Form):
    folder_name = forms.CharField(label='Nazwa folderu', max_length=100, widget = forms.TextInput( attrs={'id': 'folder_name'}))

class SectionUploadForm(forms.Form):
    section_name = forms.CharField(label='Nazwa sekcji', max_length=100, widget = forms.TextInput( attrs={'id': 'section_name'}), required=False)
    section_type = forms.CharField(label='Typ sekcji', max_length=100, widget = forms.TextInput( attrs={'id': 'section_type'}))

coding/views.py
from django.shortcuts import render
from .models import Folder, File, File_section, Section_type
from django.http import HttpResponseRedirect, FileResponse
from django.urls import reverse
from django.utils import timezone
from .forms import *
from .sdcc_options import *
import re
import os
from django.http import JsonResponse
import json

def create_structure():
    folder_list = Folder.objects.filter(parent = None).filter(available=True)
    file_list = File.objects.filter(parent = None).filter(available=True)
    result = '<ul>'
    for folder in folder_list:
        result += folder.structure()
    for file in file_list:
        result += file.structure()
    result += '</ul>'
    return result

def line_type(line):
    match = re.fullmatch(".*__asm.*", line)
    if match != None :
        return Section_type.objects.get(name = "wstawka asemblerowa")
    match = re.fullmatch("\s*\/\*.*", line)
    if match != None :
        return Section_type.objects.get(name = "komentarz")
    match = re.fullmatch("\s*#.*", line)
    if match != None :
        return Section_type.objects.get(name = "dyrektywy")
    match = re.fullmatch("\s*(int|double|float|char).*\;", line)
    if match != None :
        return Section_type.objects.get(name = "deklaracja zmiennych")
    return Section_type.objects.get(name = "procedury")

def divide_into_sections(file):
    lines = file.content.splitlines()
    section_content = ""
    counter = 1
    section_type = None
    first_line = 1
    for line in lines :
        if section_type != None:
            if section_type.name == "komentarz" and re.fullmatch(".*\*\/\s*", line) == None:
                section_content += line + '\n'
                counter = counter + 1
                continue
            if section_type.name == "komentarz" and re.fullmatch(".*\*\/\s*", line) != None:
                section_content += line + '\n'
                counter = counter + 1
                new_section = File_section(begin = first_line, end = counter - 1, type = section_type,  file = file, content=section_content)
                new_section.name = 'File id: '+ str(file.id) + ' lines: '+str(first_line)+'-'+str(counter-1)
                new_section.save()
                section_type = None
                section_content = ""
                continue
            if section_type.name == "wstawka asemblerowa" and re.fullmatch(".*__endasm;.*", line) == None:
                section_content += line + '\n'
                counter = counter + 1
                continue
            if section_type.name == "wstawka asemblerowa" and re.fullmatch(".*__endasm;.*", line) != None:
                section_content += line + '\n'
                counter = counter + 1
                new_section = File_section(begin = first_line, end = counter - 1, type = section_type,  file = file, content=section_content)
                new_section.name = 'File id: '+ str(file.id) + ' lines: '+str(first_line)+'-'+str(counter-1)
                new_section.save()
                section_type = None
                section_content = ""
                continue
        if re.fullmatch("\s*", line) != None:
            counter = counter + 1
            section_content += '\n'
            continue
        actual_line_type = line_type(line)
        if actual_line_type.name == "komentarz" and re.fullmatch(".*\*\/\s*", line):
            if section_type != None :
                new_section = File_section(begin = first_line, end = counter - 1, type = section_type,  file = file, content=section_content)
                new_section.name = 'File id: '+ str(file.id) + ' lines: '+str(first_line)+'-'+str(counter-1)
                new_section.save()
            section_type = actual_line_type
            section_content = line + '\n'
            first_line = counter
            counter = counter + 1
            new_section = File_section(begin = first_line, end = counter - 1, type = section_type,  file = file, content=section_content)
            new_section.name = 'File id: '+ str(file.id) + ' lines: '+str(first_line)+'-'+str(counter-1)
            new_section.save()
            first_line = counter
            section_type = None
            section_content = ""
            continue
        if actual_line_type == section_type :
            section_content += line + '\n'
        else :
            if section_type != None :
                new_section = File_section(begin = first_line, end = counter - 1, type = section_type,  file = file, content=section_content)
                new_section.name = 'File id: '+ str(file.id) + ' lines: '+str(first_line)+'-'+str(counter-1)
                new_section.save()
            section_type = actual_line_type
            section_content = line + '\n'
            first_line = counter
        counter = counter + 1
    new_section = File_section(begin = first_line, end = counter - 1, type = section_type,  file = file, content=section_content)
    new_section.name = 'File id: '+ str(file.id) + ' lines: '+str(first_line)+'-'+str(counter-1)
    new_section.save()

def asm_split(content) :
    first_line = 1
    content = content.splitlines()
    compile = ""
    index = 0
    for line in content:
        if line == ";--------------------------------------------------------":
            if first_line:
                if compile != "":
                    compile += "</pre></pre>"
                    index += 1
                compile += "<pre class='asm_section'>\n"
                compile += "<pre class='asm_section_header' id='asm_header_"+str(index)+"'>\n"
                compile += line + '\n'
                first_line = 0
            else:
                compile += line + '\n'
                compile += "</pre><pre class='asm_section_content show' id='asm_content_"+str(index)+"'>\n"
                first_line = 1
        else:
            if (".c:" in line):
                id = line.split(':')[1]
                compile += "<pre class='asm_line' id='asm_line_"+id+"'>" + line + '\n' + "</pre>"
            else:
                compile += line + '\n'
    if "<pre" in compile:
        return compile + "</pre></pre>\n"
    else:
        return compile

def errors_split(errors, file_name):
    result = ""
    for error in errors:
        match = re.fullmatch(".*\.c:[0-9]*:.*", error)
        if match != None:
            line_str = error.split(':')[1]
            line = int(line_str)
            if result != "":
                result += "</pre>"
            result += "<pre class='error_section' id='error_"+line_str+"'>"
            result += file_name
            splits = error.split(':')
            for i in range(1, len(splits)):
                result += ':' + splits[i]
            result += '\n'
        else:
            result += error + "\n"
    if "<pre" in result:
        result += "</pre>\n"
    return result

def index(request):
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(reverse("coding:login"))
    structure = create_structure()
    context = {
        'structure': structure,
        'standard_form': StandardForm(initial={'standard': request.session['standard']}),
        'optymalizacje_form': OptymalizacjeForm(initial={'optymalizacje': request.session['optymalizacje']}),
        'procesor_form': ProcesorForm(initial={'procesor': request.session['procesor']}),
        'z80_form': Z80Form(initial={'z80': request.session['z80']}),
        'stm8_form': STM8Form(initial={'stm8': request.session['stm8']}),
        'mcs51_form': MCS51Form(initial={'mcs51': request.session['mcs51']}),
        'file_form': FileUploadForm(),
        'folder_form': FolderUploadForm(),
        'section_form': SectionUploadForm(),
    }
    return render(request, "coding/index.html", context)

def file(request, file_id):
    file = File.objects.get(pk=file_id)
    context = {
        # 'content': file.write_sections(),
        'content': file.content,
    }
    return JsonResponse(context)

def save_file(request, file_id):
    data = json.loads(request.body)
    file = File.objects.get(pk=file_id)
    file.content = data['content']
    file.modification_date = timezone.now()
    file.save()
    # divide_into_sections(file)
    context = {}
    return JsonResponse(context)

def add_folder(request):
    data = json.loads(request.body)
    parent_id = data['parent_id']
    if parent_id == 0:
        parent_folder = None
    else:
        parent_folder = Folder.objects.get(pk=parent_id)
    if request.user.is_authenticated:
        current_user = request.user
    else:
        current_user = None
    name = data['name']
    new_folder = Folder(name=name, parent=parent_folder, user=current_user)
    new_folder.save()
    structure = create_structure()
    context = {
        'structure': structure,
        'folder_id': new_folder.id,
    }
    return JsonResponse(context)

def add_file(request):
    data = json.loads(request.body)
    parent_id = data['parent_id']
    if parent_id == 0:
        parent_folder = None
    else:
        parent_folder = Folder.objects.get(pk=parent_id)
    if request.user.is_authenticated:
        current_user = request.user
    else:
        current_user = None
    file = data['file']
    name = data['name']
    new_file = File(name=name, parent=parent_folder, content=file, user = current_user)
    new_file.save()
    # divide_into_sections(new_file)
    structure = create_structure()
    context = {
        'structure': structure,
        'file_id': new_file.id,
        'content': new_file.content,
        # 'file_content': new_file.write_sections(),
    }
    return JsonResponse(context)

def add_section(request, file_id):
    data = json.loads(request.body)
    first_line = data['first_line']
    last_line = data['last_line']
    name = data['name']
    type = data['type']
    error = 0
    file = File.objects.get(pk=file_id)

coding/templates/coding/base.html
<!DOCTYPE html>
<html lang="pl">

<head>
  <meta charset="UTF-8">

  {% load static %}
  <link rel="stylesheet" href="{% static 'coding/style.css' %}">

  <title>Projekt</title>
</head>

<body>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>

coding/templates/coding/index.html
<!DOCTYPE html>
<html lang="pl">

<head>
  <meta charset="UTF-8">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.0/codemirror.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.0/codemirror.min.js"></script>

  {% load static %}
  <link rel="stylesheet" href="{% static 'coding/style.css' %}">
  </link>

  <title>Projekt</title>
</head>

<body>
  <input type="checkbox" id="theme-switch" class="theme-switch">

  <div id="page">

    <header id="menu_bar">
      <div class="dropdown">
        <button class="block menu" onclick="plikFunction()" id="plikDropbutton">Plik
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content" id="plikDropdown">
          <button type="submit" id="file_upload" onclick="showFileUpload()">Dodaj plik</button>
          <button type="submit" id="folder_upload" onclick="showFolderUpload()">Dodaj katalog</button>
          <button type="submit" class="hidden" id="compile" onclick="save_file()">Zapisz</button>
          <button type="submit" class="hidden" id="save" onclick="compile()">Kompiluj</button>
          <button type="submit" class="hidden" id="download" onclick="download()">Pobierz plik .asm</button>
          <button type="submit" class="hidden" id="delete_file" onclick="delete_file()">Usuń plik</button>
          <!-- <button type="submit" class="hidden" id="delete_section" onclick="delete_section()">Usuń sekcję</button> -->
          <!-- <button type="submit" class="hidden" id="add_section" onclick="show_add_section()">Dodaj sekcję</button> -->
          <button type="submit" class="hidden" id="delete_folder" onclick="delete_folder()">Usuń katalog</button>
        </div>
      </div>
      <div class="dropdown">
        <button class="block menu" onclick="edycjaFunction()" id="edycjaDropbutton">Edycja
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content" id="edycjaDropdown">
        </div>
      </div>
      <div class="dropdown">
        <button class="block menu" onclick="opcjeFunction()" id="opcjeDropbutton">Opcje
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content" id="opcjeDropdown">
        </div>
      </div>
      <label for="theme-switch" id="switch-label" class="block menu"></label>
      <form action="{% url 'coding:logout' %}" id="logout">
        <button type="submit" class="block menu">Wyloguj</button>
      </form>

    </header>
    <div id="navigation">
      {{structure | safe}}
    </div>

    <div id="program">
      <p class="info" id="add_section_info">Najpierw zaznacz fragment pliku</p>
      <p class="info" id="add_section_error">Nowa sekcja musi zawierać istniejące już sekcje w całości lub zawierać się
        w całości w już istniejącej sekcji</p>
      <!-- <pre id="file_content" class="program_content"> Wybierz plik z listy po lewej stronie</pre> -->
      <div id="file_content" class="program_content">Wybierz plik z listy po lewej stronie</div>
    </div>

    <div id="fragment">
      <div id="fragment_buttons">
        <button type="submit" id="show_asm_button" onclick="show_asm()">Rozwiń sekcje</button>
        <button type="submit" id="hide_asm_button" onclick="hide_asm()">Zwiń sekcje</button>
      </div>
      <div id="fragment_content"></div>
    </div>

    <div id="tabs">
      <button class="block tab chosen" id="standard" onclick="standardFunction()">
        STANDARD
      </button>
      <button class="block tab" id="optymalizacje" onclick="optymalizacjeFunction()">
        OPTYMALIZACJE
      </button>
      <button class="block tab" id="procesor" onclick="procesorFunction()">
        PROCESOR
      </button>
      <button class="block tab" id="zalezne" onclick="zalezneFunction()">
        ZALEŻNE
      </button>
    </div>
    <div class="tab_window" id="standard_tab">
      <form id="standard_form" method="post">
        <fieldset>
          {% csrf_token %}
          <legend>{{standard_form.legend}}</legend>
          <div>
            {% for choice in standard_form.standard %}
            {{choice}}
            {% endfor %}
          </div>
        </fieldset>
        <button type="submit">Zatwierdź</button>
      </form>
    </div>
    <div class="tab_window" id="optymalizacje_tab">
      <form id="optymalizacje_form" method="post">
        <fieldset>
          {% csrf_token %}
          <legend>{{optymalizacje_form.legend}}</legend>
          <div>
            {% for choice in optymalizacje_form.optymalizacje%}
            {{choice}}
            {% endfor %}
          </div>
        </fieldset>
        <button type="submit">Zatwierdź</button>
      </form>
    </div>
    <div class="tab_window" id="procesor_tab">
      <form id="procesor_form" method="post">
        <fieldset>
          {% csrf_token %}
          <legend>{{procesor_form.legend}}</legend>
          <div>
            {% for choice in procesor_form.procesor%}
            {{choice}}
            {% endfor %}
          </div>
        </fieldset>
        <button type="submit">Zatwierdź</button>
      </form>
    </div>
    <div class="tab_window" id="zalezne_tab">
      <form class="zalezne_form" id="z80_form" method="post">
        <fieldset>
          {% csrf_token %}
          <legend>{{z80_form.legend}}</legend>
          <div>
            {% for choice in z80_form.z80%}
            {{choice}}
            {% endfor %}
          </div>
        </fieldset>
        <button type="submit">Zatwierdź</button>
      </form>
      <form class="zalezne_form" id="stm8_form" method="post">
        <fieldset>
          {% csrf_token %}
          <legend>{{stm8_form.legend}}</legend>
          <div>
            {% for choice in stm8_form.stm8%}
            {{choice}}
            {% endfor %}
          </div>
        </fieldset>
        <button type="submit">Zatwierdź</button>
      </form>
      <form class="zalezne_form" id="mcs51_form" method="post">
        <fieldset>
          {% csrf_token %}
          <legend>{{mcs51_form.legend}}</legend>
          <div>
            {% for choice in mcs51_form.mcs51%}
            {{choice}}
            {% endfor %}
          </div>
        </fieldset>
        <button type="submit">Zatwierdź</button>
      </form>
      <div class="zalezne_form show" id="zalezne_info">
        <p>Wybierz procesor, aby zobaczyć zależne od niego opcje</p>
      </div>
    </div>

    <div id="blur">
      <div class="add" id="fileUpload">
        <form method="post" enctype="multipart/form-data" id="file_form">
          {% csrf_token %}
          <legend>
            <h1>Dodaj plik</h1>
          </legend><br>
          <div>
            {{ file_form.file_name.label_tag }}
            {{ file_form.file_name }}
          </div>
          <br>
          <div>
            {{ file_form.file.label_tag }}
            {{ file_form.file }}
          </div>
          <br>
          <button type="submit">Dodaj</button>
          <button type="button" onclick="showFileUpload()">Anuluj</button>
        </form>
      </div>
      <div class="add" id="folderUpload">
        <form method="post" enctype="multipart/form-data" id="folder_form">
          {% csrf_token %}
          <legend>
            <h1>Dodaj katalog</h1>
          </legend><br>
          <div>
            {{ folder_form.folder_name.label_tag }}
            {{ folder_form.folder_name }}
          </div>
          <br>
          <button type="submit">Dodaj</button>
          <button type="button" onclick="showFolderUpload()">Anuluj</button>
        </form>
      </div>
      <div class="add" id="sectionUpload">
        <form method="post" enctype="multipart/form-data" id="folder_form">
          {% csrf_token %}
          <legend>
            <h1 id="section_legend"></h1>
          </legend><br>
          <div>
            {{ section_form.section_name.label_tag }}
            {{ section_form.section_name }}
          </div>
          <div>
            {{ section_form.section_type.label_tag }}
            {{ section_form.section_type }}
          </div>
          <br>
          <button type="submit">Dodaj</button>
          <button type="button" onclick="showSectionUpload()">Anuluj</button>
        </form>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/lib/codemirror.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/lib/codemirror.css">
  <script type="text/javascript" src="{%static 'coding/script.js' %}">
  </script>
</body>

</html>

coding/templates/coding/login.html
{% extends "base.html" %}

{% block content %}



<!-- {% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %} -->

<form method="post" action="{% url 'coding:login' %}" id="login_form">
    {% csrf_token %}
    <table id="login_table">
        {% if form.errors %}
        <tr>
            <td colspan="2">
                <p id="login_error">Your username and password didn't match. Please try again.</p>
            </td>
        </tr>
        {% endif %}
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>

    <input type="submit" value="Zaloguj">
    <input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock %}